openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Panthera'
  description: 'Testing API'
  
servers:
  - url: https://panthera.herokuapp.com/api
  - url: http://localhost:3000/api
  
paths: 
  /tasks:
    get: 
      summary: Gets all Tasks
      parameters:
        - name: pageNumber
          in: query
          required: false
          description: The page number to return
          schema:
            type: integer
        - name: pageSize
          in: query
          required: false
          description: The number of results to return
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string

    post:
      summary: Create a new task
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
        '400':
          description: Invalid request

  /tasks/{id}:
    get:
      summary: Returns a task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the task to return
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
        '400':
          description: Invalid request
        '404':
          description: Not Found

    put:
      summary: Update a task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the task to return
          schema:
            type: integer
      responses:
        '201':
          description: OK
        '400':
          description: Invalid request
        '404':
          description: Not Found

    delete:
      summary: Delete a task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the task to return
          schema:
            type: integer
      responses:
        '204':
          description: OK
        '400':
          description: Invalid request